version: '3.8'

services:
  # Eureka Server
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - backend-network

  # Books Catalogue Service
  ms-books-catalogue:
    build: ./ms-books-catalogue
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d1jl8ha4d50c7385lre0-a/books_catalogue
      - SPRING_DATASOURCE_USERNAME=books_catalogue_user
      - SPRING_DATASOURCE_PASSWORD=a1ieV3GOZFu7s88NEfHmvy375liyDA29
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - backend-network

  # Books Payments Service
  ms-books-payments:
    build: ./ms-books-payments
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d1jla76mcj7s73a08o7g-a/books_payments
      - SPRING_DATASOURCE_USERNAME=books_payments_user
      - SPRING_DATASOURCE_PASSWORD=9beJjtdB6XbywyykZkNFCqSOqhXYHWAo
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - backend-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - ms-books-catalogue
      - ms-books-payments
    networks:
      - backend-network

  # Nginx - Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
      - eureka-server
      - ms-books-catalogue
      - ms-books-payments
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge 