server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: books-catalogue
          uri: lb://books-catalogue
          predicates:
            - Path=/api/books/**
          filters:
            - StripPrefix=1
        - id: books-payments
          uri: lb://books-payments
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true 